#!/bin/sh

decrypt() {
    path=${1:-.}
    find $path -type f -name puzzle\*.in.gpg | gpg --batch --decrypt --multifile --no --quiet
}

encrypt() {
    path=${1:-.}
    find $path -type f -name puzzle\*.in | gpg --batch --default-recipient-self --encrypt --multifile --no --quiet
}

case "$1" in
    encrypt|enc|e)
        shift
        encrypt "$@"
        ;;
    decrypt|dec|d)
        shift
        decrypt "$@"
        ;;
    *)
        echo "Usage: $0 decrypt|encrypt"
        exit 1
        ;;
esac
