#!/bin/sh

if [ -z "$1" ]; then
    echo "Usage: $0 program"
    exit 1
fi

PROG=$(realpath -s $1)
if [ ! -x $PROG ]; then
    echo "No executable $PROG found"
    exit 1
fi

PROG_ID=$2
if [ -z "$PROG_ID" ]; then
    PROG_ID=$(basename ${PROG%.*})
fi

cd $(dirname $0)

case $(basename $0) in
    run)
        OUT_CMD="cat"
        ;;
    xrun)
        OUT_CMD="hexdump -C"
        ;;
esac

for IN_FILE in $PROG_ID/*.in; do
    TEST_ID=${IN_FILE%.*}
    ENV_FILE=$TEST_ID.env
    OUT_FILE=$TEST_ID.out
    if [ ! -f $OUT_FILE -o ! -r $IN_FILE ]; then
        continue
    fi
    if [ -r $ENV_FILE ]; then
        echo "==== $TEST_ID < $ENV_FILE ===="
        PROG_OUT=$(export $(xargs < $ENV_FILE) && $PROG < $IN_FILE | $OUT_CMD)
    else
        echo "==== $TEST_ID ===="
        PROG_OUT=$($PROG < $IN_FILE | $OUT_CMD)
    fi
    EXPECT_OUT=$($OUT_CMD $OUT_FILE)
    if [ "$PROG_OUT" != "$EXPECT_OUT" ]; then
        echo ---- Program Output ----
        echo $PROG_OUT
        echo ------------------------
        echo ---- Expected Output ---
        echo $EXPECT_OUT
        echo ------------------------
        exit 1
    fi
done
